name: arl-next-dev
version: '3.8'

services:
  arl-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: arl-web
    command: bash -c "/code/backend/start_web.sh"
    working_dir: /code
    dns:
      - 223.5.5.5
      - 119.29.29.29
      - 114.114.114.114
    volumes:
      - ./:/code
    ports:
      - "5001:5000"
      - "8081:8080"
      - "8082:80"
    environment:
      - TZ=Asia/Shanghai
      - DEBIAN_FRONTEND=noninteractive
      - NO_PROXY=localhost,127.0.0.1,icp_query,mongodb,rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
      - icp_query

  arl-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: arl-worker
    command: bash -c "/code/backend/start_worker.sh"
    working_dir: /code
    dns:
      - 223.5.5.5
      - 119.29.29.29
      - 114.114.114.114
    volumes:
      - ./:/code
    environment:
      - TZ=Asia/Shanghai
      - DEBIAN_FRONTEND=noninteractive
      - NO_PROXY=localhost,127.0.0.1,icp_query,mongodb,rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
      - icp_query

  mongodb:
    image: mongo:4.0.27
    container_name: arl_mongodb_dev
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=arl
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - TZ=Asia/Shanghai
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: arl_rabbitmq_dev
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - TZ=Asia/Shanghai
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit consumer_timeout 36000000

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  icp_query:
    build: ./backend/icp_query
    container_name: arl_icp_query_dev
    restart: always
    ports:
      - "16182:16181"

volumes:
  mongo_data:
  rabbitmq_data:
